### ISSUE TITLE
[Bug]login failed

### ISSUE THREAD

**Issue by IoT-CI-Ltd** [JEMcats/ubox_camera_api#3]
Hi,

First, thanks for your work on this. Annoying that these camera's don't expose readily available stream.

I am however having some issues with this running on Ubuntu.

I have all the .env file all running but keep getting:

Response received: {
  code: 20005,
  data: { failed_count: 2, allow_try_count: 30, deny_retry_in_seconds: 0 },
  msg: 'Invalid account or password(20005)'
}
Login failed: Invalid account or password(20005)

I created the account using the Mobile App (iOs).

I had initially configured the camera and account via the i-Cam app, but then deregistered and then configured using the https://apps.apple.com/us/app/ubox/id1436112326 

I have also logged in successfully with the creds in the .env file here: https://api-us.ubianet.com/public/login

Have I missed a step somewhere?

Many thanks

**Comment by JEMcats** [comment]
Did you create your account using Apple, Google, Etc?

**Comment by IoT-CI-Ltd** [comment]
also, I cannot see that users.json file is being created as these are the contents of the directory 

api_docs         LICENSE   node_modules  package-lock.json  server.js
CONTRIBUTING.md  login.js  package.json  README.md

**Comment by JEMcats** [comment]
If the login fails the users.json will not be created. If you give me a minute I will get back to you with some troubleshooting steps 🙂.

**Comment by IoT-CI-Ltd** [comment]
cool, thanks, no rush here really, just let me know if I can help test at all

**Comment by JEMcats** [comment]
Do you have access to a code editor?

**Comment by JEMcats** [comment]
If you do could you paste this code under line ```28```
```
console.log('email',process.env.email)
console.log('password',process.env.password)
```
after that run login.js again and check that the email and password match what is in the env file.

**Comment by IoT-CI-Ltd** [comment]
sorry, which file should I insert under line28?

I can nano files on this machine but very little more at present

**Comment by JEMcats** [comment]
login.js

**Comment by IoT-CI-Ltd** [comment]
const email = process.env.email;
const password = hmacSha1Base64(process.env.password);
console.log(password)
console.log('email',process.env.email)
console.log('password',process.env.password)


so that section should look like this?

**Comment by JEMcats** [comment]
Yes

**Comment by JEMcats** [comment]
now try running login.js again

**Comment by IoT-CI-Ltd** [comment]
yes, those creds returned are correct

**Comment by JEMcats** [comment]
can you go to [Sha1 Conversion Tool](https://emn178.github.io/online-tools/sha1.html) and select these options:
![Screenshot 2024-10-21 at 5 34 10 PM](https://github.com/user-attachments/assets/85a113e0-2b7c-47a9-924d-c321c1b8ab14) enter your password and hash it please then check if it matches the string logged by ```console.log(password)```

**Comment by IoT-CI-Ltd** [comment]
it is the same apart from the = at the end which is not displayed in the console but displayed when I use the Hashtool

**Comment by JEMcats** [comment]
I have just updated the code, please remove the current directory and follow the setup instructions again

**Comment by IoT-CI-Ltd** [comment]
so in password line it should be

password=HASSHEDPASSWORD replaced to ','

?

**Comment by JEMcats** [comment]
when you hash you get ```HASHEDPASSWORD=``` just change it to ```HASSHEDPASSWORD,``` and set that in your env file

**Comment by IoT-CI-Ltd** [comment]
Response received: {
  code: 20005,
  data: { failed_count: 3, allow_try_count: 30, deny_retry_in_seconds: 0 },
  msg: 'Invalid account or password(20005)'
}
Login failed: Invalid account or password(20005)

**Comment by JEMcats** [comment]
did you delete the directory and run the git clone command again?

**Comment by IoT-CI-Ltd** [comment]
yes

**Comment by JEMcats** [comment]
Did you add the 
```
debug_mode=true
```
to the env file?

**Comment by IoT-CI-Ltd** [comment]
yes, one se, just doing all that again to make sure

**Comment by IoT-CI-Ltd** [comment]
Yea, jiust redid all of that and it is the same response

i do see this on npm install command


ubox_camera_api$ npm install
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

?

**Comment by IoT-CI-Ltd** [comment]
another thing, when I login here: https://api-us.ubianet.com/public/login all i get is a flash "Success" and then it goes back to the login page. I assume that this is normal?

**Comment by JEMcats** [comment]
I never knew about that webpage, but its not the api i used.

**Comment by JEMcats** [comment]
> Yea, jiust redid all of that and it is the same response
> 
> i do see this on npm install command
> 
> ubox_camera_api$ npm install npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
> 
> ?

You dont need to worry about that, its normal.

**Comment by IoT-CI-Ltd** [comment]
THe only other thing I can think of is country selection that would be different, Have I used the right app to create the account?

**Comment by JEMcats** [comment]
You have used the correct app, what country do you select when you login?

**Comment by JEMcats** [comment]
The only one i have tested is United States

**Comment by IoT-CI-Ltd** [comment]
United Kingdom

Let me try with US and see if that does anything

**Comment by IoT-CI-Ltd** [comment]
no, don't think country makes a difference

**Comment by IoT-CI-Ltd** [comment]
Do you have the config for postman to hit their API?

**Comment by JEMcats** [comment]
Yes, you can find it in the [api_docs directory](https://github.com/JEMcats/ubox_camera_api/tree/main/api_docs/). The login request is under [```portal.ubianet.com/api/v2/user/login.json```](https://github.com/JEMcats/ubox_camera_api/tree/main/api_docs/portal.ubianet.com/api/v3/login.json).

**Comment by JEMcats** [comment]
I would try resetting your uBox account password if possible and then update the env file values to look like:
```
email=YOUR_EMAIL
password=YOUR_NEW_PASSWORD (not hashed)
debug_mode=false
```

**Comment by IoT-CI-Ltd** [comment]
msg: 'success'

My initial password had a special character in it. I updated the password from the app excluding any special characters and it worked! 

I often come across special character complications when using some platforms from China. I am not saying that it is this specifically, but ultimately, resetting the password fixed the issue. Thanks for all your help and hard work on this!

**Comment by JEMcats** [comment]
Your welcome. Have a nice day!

**Comment by IoT-CI-Ltd** [comment]
Sorry, one last question, in postman then when I query the server, what do I place in the JSON body?
