### ISSUE TITLE
[Bug] login failed

### ISSUE THREAD

**Issue by cwtufts** [JEMcats/ubox_camera_api#7]
Response received: {
  code: 20005,
  data: { failed_count: 1, allow_try_count: 30, deny_retry_in_seconds: 0 },
  msg: 'Invalid account or password(20005)'
}
Login failed: Invalid account or password(20005)

Have tried changing the password and still getting the error. Checked the password hash and it is the same. What else could the issue be?

**Comment by cwtufts** [comment]
I did notice that when I run debug=true both passwords are the password that is put into the .env file neither one are hashed. Cannot get a login success message have changed the password twice with no special characters.

**Comment by JEMcats** [comment]
When in debug mode hashing is disabled.
Try setting the value for the password in the ```.env``` file to your uBox password and then try running the hashing tool with:
```
$ node hash_password.js
```
Copy the password that is in the command line output and put it as the value for the password in the ```.env``` file, then try running with ```debug=true```

**Comment by cwtufts** [comment]
Still returning the same error.

**Comment by cwtufts** [comment]
![image](https://github.com/user-attachments/assets/b7f6eb7b-89d1-4436-95d0-42f484cce1ef)

Same error either way. Debug=true with the hash. And debug=false without the hash

**Comment by JEMcats** [comment]
Is the email matching what you signed up with?

**Comment by cwtufts** [comment]
Yes they match perfectly. Checked for typos and everything.

**Comment by JEMcats** [comment]
Try running:
```
$ curl --location 'https://portal.ubianet.com/api/v3/login' \
--header 'Content-Type: application/json' \
--data '{
        "account": "Email",
        "password": "Hashed-Password",
        "lang": "en",
        "app": "ubox",
        "device_type": 2
    }'
```
in your command line.

**Comment by cwtufts** [comment]
{"code":10021,"data":{},"msg":"Account format error(10021)"}c

**Comment by JEMcats** [comment]
did you replace ```Email``` and ```Hashed-Password``` with the correct details?

**Comment by cwtufts** [comment]
I had not. That was my bad. After putting the details in this is the output. 


{"code":10001,"data":{},"msg":"invalid params(10001)"}

**Comment by JEMcats** [comment]
you mentioned in your first comment that you had tried reseting the password, did you reset it using the uBox app on your mobile device?

**Comment by cwtufts** [comment]
Yes I did. Under the security tab on the app.

**Comment by JEMcats** [comment]
did you change your password to something that it has never been before?

**Comment by cwtufts** [comment]
Yes. Come up with a new password entirely just to make sure.

**Comment by JEMcats** [comment]
In the photo you provided above, your hashed password was: ```Bsmb9AVZPLquOT/TbG03fNABz4c,``` I have never seen a slash in a password before, try changing the password in your .env to ```Bsmb9AVZPLquOT,``` or ```TbG03fNABz4c,```, try both while debug is set to true. Please make sure you keep the comma at the end of the passwords

**Comment by JEMcats** [comment]
if that doesn't work you should try using [proxyman](https://proxyman.io/download) to check the requests being made by your phone, follow their setup instructions, once setup sign out of the uBox app and with the proxy running log back in. In Proxyman look for any requests being made to ```portal.ubianet.com``` specifically to the ```/api/v3/login``` path. You may need to enable ssl proxying for that domain and then logout and back in again. Once you see the request you can look at the response body:
<img width="516" alt="Screenshot 2024-12-27 at 1 38 28 PM" src="https://github.com/user-attachments/assets/57360a53-2319-4ddd-a2cc-ca86fff106b8" />

**Comment by cwtufts** [comment]
So I started messing with the online hash tool and figured out that if I put numbers into the password it adds the / this throws it off so I changed the password to be something that would only give regular characters on the hash tool and it seems to have fixed the issue. Because now it let me login. Had to make sure that there were no special characters in the hash as well.

**Comment by JEMcats** [comment]
Great, would you like me to close this issue?

**Comment by cwtufts** [comment]
Yes, you can! Thank you!
